hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

#fos_oauth_server_token:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

#fos_oauth_server_authorize:
#    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

loopanime_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: LoopAnimeUsersBundle:Security:login }

loopanime_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: LoopAnimeUsersBundle:Security:loginCheck }

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

loop_anime_welcome:
    resource: "@LoopAnimeWelcomeBundle/Resources/config/routing.yml"
    prefix:   /welcome/

loop_anime_admin:
    resource: "@LoopAnimeAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

loop_anime_search:
    resource: "@LoopAnimeSearchBundle/Resources/config/routing.yml"
    prefix:   /search

loop_anime_comments:
    resource: "@LoopAnimeCommentsBundle/Resources/config/routing.yml"
    prefix:   /comments/

loop_anime_users:
    resource: "@LoopAnimeUsersBundle/Resources/config/routing.yml"
    prefix:   /

loop_anime_shows:
    resource: "@LoopAnimeShowsBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
