services:
    loopanime.registration.form.type:
        class: LoopAnime\UsersBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%, "@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: loopanime_user_registration }
    loopanime.registration.form.handler:
        class: LoopAnime\UsersBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator", "@doctrine.orm.entity_manager", "@event_dispatcher"]
        scope: request
        public: false
    loopanime.invitation.form.type:
        class: LoopAnime\UsersBundle\Form\Type\InvitationFormType
        arguments: [@loopanime.invitation.form.data_transformer]
        tags: [{ name: "form.type", alias: "loopanime_invitation_type" }]
    loopanime.invitation.form.data_transformer:
        class: LoopAnime\UsersBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: [@doctrine.orm.entity_manager]
    my_user_provider:
        class: LoopAnime\UsersBundle\Security\Core\User\FOSUBUserProvider
        arguments: ["@fos_user.user_manager",{facebook: facebook_id, google: google_id},"@event_dispatcher"]
    loopanime.users.listener.user_listener:
        class: LoopAnime\UsersBundle\Event\EventListener\UserListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: user.create, method: onUserCreate }
            - { name: kernel.event_listener, event: user.connect, method: onUserConnect }
