loop_anime_shows_homepage:
    pattern:  /
    defaults: { _controller: LoopAnimeShowsBundle:Anime:index }
loop_anime_shows_list:
    pattern: /animes/list/
    defaults: { _controller: LoopAnimeShowsBundle:Anime:ListAnimes }
loop_anime_shows_categories:
    pattern: /animes/categories/
    defaults: { _controller: LoopAnimeShowsBundle:Anime:ListCategories }
