liip_imagine:
    filter_sets:
        original:
            quality: 100
            filters:
                strip: ~
                relative_resize: { scale: 1 }
        featuredAnime:
            quality: 100
            filters:
                strip: ~
                thumbnail: { size: [360, 200], mode: outbound }
        animePagePoster:
            quality: 100
            filters:
                strip: ~
                thumbnail: { size: [310, 240], mode: outbound }
        20x20f:
            quality: 100
            filters:
                strip: ~
                thumbnail: { size: [20, 20], mode: outbound }
        100x100f:
            quality: 80
            filters:
                strip: ~
                thumbnail: { size: [100, 100], mode: outbound }
